# Site information
title: Elvis is still in the building
email: me@elvishsu.com
description: A simple yet creative software designer
baseurl: ""
author:
  name: Elvis Hsu
  twitter: elvishsu
twitter:
  username: elvishsu66
  card: summary
disqus:
  shortname: elvishsu66
logo: /assets/icon/favicon.webp
atom_path: /blog/atom.xml
social:
  name: Elvis Hsu
  links:
    - https://twitter.com/elvishsu
    - https://www.linkedin.com/in/elvishsu
    - https://github.com/elvishsu66

# Site settings
permalink: /blog/:title.html
markdown: kramdown
paginate: 6
paginate_path: "/blog/page:num/"
date_format: "%-d %b, %Y"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]

google_analytics: G-M47EN9ZR37





navigation:
  - title: home
    url: /
  - title: blog
    url: /blog/
  - title: categories
    url: /blog/categories
  - title: about
    url: /about
