# Site information
title: Elvis is still in the building
logo: /assets/images/elvis.jpg
email: me@elvishsu.com
description: A simple yet creative software designer
baseurl: ""
url: "https://elvishsu.com"
author:
  name: Elvis Hsu
atom_path: /blog/atom.xml

# Site settings
permalink: /blog/:title.html
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
date_format: "%-d %b, %Y"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]

google_analytics: G-M47EN9ZR37

disqus:
  shortname: elvishsu66

navigation:
  - title: home
    url: /
  - title: blog
    url: /blog/
  - title: categories
    url: /blog/categories
  - title: about
    url: /about
