# Site information
title: Elvis is still in the building
logo: /assets/images/elvis.jpg
email: me@elvishsu.com
description: A simple yet creative software designer
baseurl: ""
url: "https://elvishsu.com"
author:
  name: Elvis Hsu
atom_path: /blog/atom.xml

# Site settings
permalink: /blog/:title.html
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

google_analytics: G-M47EN9ZR37

disqus:
  shortname: elvishsu66