# Site information
title: Elvis is still in the building
logo: /assets/images/elvis.jpg
email: me@elvishsu.com
description: A simple yet creative software designer
baseurl: ""
url: "https://elvishsu.com"

# Site settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/:num/"
date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: G-M47EN9ZR37

disqus:
  shortname: elvishsu66